Repository vuex-orm/vuex-orm-next, pull requests merged in 2021-11, with the labels that each got.

#92 Polymorphic One to One Documentation
  docs/.vuepress/config.js
  docs/guide/model/decorators.md
  docs/guide/relationships/polymorphic.md
Labels: documentation

#94 Add `withAll()` and `withAllRecursive()` to Query Builder
  src/query/Query.ts
  src/repository/Repository.ts
  test/feature/relations/eager_loads/eager_loads_all.spec.ts
  test/feature/relations/eager_loads/eager_loads_recursive.spec.ts
Labels: enhancement

#99 build(deps): bump packages
  package.json
  yarn.lock
Labels: dependencies

#100 docs: loading all relationships
  docs/guide/relationships/getting-started.md
Labels: documentation

#98 Remove Database from Model
  docs/guide/repository/deleting-data.md
  src/database/Database.ts
  src/model/Model.ts
  src/query/Query.ts
  src/repository/Repository.ts
  test/feature/model/deletes_delete.spec.ts
  test/feature/model/deletes_delete_composite_key.spec.ts
  test/unit/model/Model.spec.ts
  test/unit/repository/Repository.spec.ts
Labels: enhancement

#102 fix: missing Attribute exports
  src/index.cjs.ts
  src/index.ts
Labels: bug

#103 feat: add relations to plugin scope
  src/plugin/Plugin.ts
Labels: enhancement

#104 fix: export missing decorator
  src/index.cjs.ts
Labels: bug
