Repository vuex-orm/vuex-orm-next, pull requests merged in 2021-04, with the labels that each got.

#58 fix(repository): implement missing `add` & `replace` methods
  src/model/Model.ts
  src/query/Query.ts
  src/repository/Repository.ts
  src/schema/Schema.ts
  test/feature/repository/inserts_add.spec.ts
  test/feature/repository/inserts_add_composite_key.spec.ts
  test/feature/repository/inserts_add_uid.spec.ts
  test/feature/repository/inserts_replace.spec.ts
  test/feature/repository/inserts_replace_composite_key.spec.ts
  test/feature/repository/inserts_replace_uid.spec.ts
Labels: bug, enhancement

#53 feat: Add support for multiple databases
  src/connection/Connection.ts
  src/database/Database.ts
  src/interpreter/Interpreter.ts
  src/model/Model.ts
  src/query/Query.ts
  src/repository/Repository.ts
  src/store/Store.ts
  src/types/vuex.ts
  test/unit/model/Model.spec.ts
  test/unit/repository/Repository.spec.ts
Labels: enhancement

#61 fix: normalization error on nested relationship
  src/schema/Schema.ts
  test/regression/normalizing_nested_relations_missing_parent_model.spec.ts
Labels: bug
